export const columns = [
   {
      field: 'employee_name',
      headerName: 'Name',
      width: 180,
      headerClassName: 'header',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-line',
      sortable: false,
      filter: false,
   },
   {
      field: 'employee_email',
      headerName: 'Email',
      width: 180,
      headerClassName: 'header',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-line',
      sortable: false,
      filter: false,
   },
   {
      field: 'employee_number',
      headerName: 'Phone',
      width: 180,
      headerClassName: 'header',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-line',
      sortable: false,
      filter: false,
   },
   {
      field: 'employee_role',
      headerName: 'role',
      width: 180,
      headerClassName: 'header',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-line',
      sortable: false,
      filter: false,
   },
   {
      field: 'employee_status',
      headerName: 'Status',
      width: 180,
      headerClassName: 'header',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-line',
      sortable: false,
      filter: false,
   },
   {
      field: 'employee_type',
      headerName: 'Type',
      width: 180,
      headerClassName: 'headerlast',
      headerAlign: 'center',
      align: 'center',
      cellClassName: 'column-linelast',
      sortable: false,
      filter: false,
   },
]
